# Generated by Django 4.1.7 on 2023-04-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movies",
            name="api_id",
            field=models.IntegerField(),
        ),
    ]
